# Generated by Django 2.2.24 on 2021-12-04 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('age', models.SmallIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('classid', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 't_stu',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('phone', models.CharField(max_length=16)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 't_users',
            },
        ),
    ]
