# Generated by Django 2.2.24 on 2022-04-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allusers',
            name='account',
        ),
        migrations.AddField(
            model_name='allusers',
            name='phone',
            field=models.CharField(default='000', max_length=16, verbose_name='手机号'),
        ),
    ]
