# Generated by Django 2.2.24 on 2022-04-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220430_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allusers',
            old_name='departId',
            new_name='depart',
        ),
    ]
