# Generated by Django 2.2.24 on 2022-04-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220430_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='create_time',
            field=models.DateTimeField(verbose_name='入职时间'),
        ),
    ]
