# Generated by Django 2.2.24 on 2022-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220430_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='create_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
    ]
