# Generated by Django 2.2.24 on 2022-05-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20220505_1921'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prettynum',
            table='t_prettynum',
        ),
    ]
